# Generated by Django 3.2.2 on 2021-05-16 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_of_submission',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='order',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
